### ISSUE TITLE
Modifica file "Guida per lo studente.md"

### ISSUE THREAD

**Issue by Elia-Valenza26** [softeng2223-inf-uniba/progetto2223-bernerslee#6]
**Si vuole**
Modificare il file markdown ./docs/Guida per lo studente.md
**Per:**
Personalizzare le figure in cui compare un nome di repository diverso dal proprio, oppure uno username o immagine di profilo diverso da quello dei componenti del gruppo.

**Comment by Elia-Valenza26** [comment]
@Fra-Sq credo che tu debba fare il revert dell'ultimo commit e riapplicare le modifiche revertate. Perchè a quanto pare sembra che alcune modifiche abbiano "rotto" la repo. Infatti dopo aver pullato mi sono accorto che nella repo locale (nell'area di staging) risultano modificati tre file : ManageAccess.png, PackageSettings.png, cloneusingurl.PNG. 
Quasi sicuramente è avvenuto un conflitto tra il repository locale e quello remoto, in quanto i file hanno lo stesso nome.

**Comment by Strix89** [comment]
Ok allora procedo io a fixxare questa cosa direttamente dal codespace di github
